from typing import TypedDict, Annotated, List, Dict, Any
import operator
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    """This dictionary defines the shared state for the LangGrapg agents.
    Annotated [List, Operator.add] tells LangGraph to append new items to the list rather than
    overwriting it when a node updates the state. 
    """

    #Path to the CSV/EXCEL file being analyzed
    dataset_path : str

    #Tracks the conversation history and generated the python code from agents
    messages: Annotated[List[BaseMessage], operator.add]

    #Data Profile (columns, data types, missing values) generated by the profiler
    schema_info: Dict[str, Any]

    #Statistical findings and insights generated by the analyst
    findings:Annotated[List[str], operator.add]

    #File paths to the PNGs generated by the Visualizer
    chart_paths: Annotated[List[str], operator.add]

    #Error logs captured from the code execution sandbox
    errors: Annotated[List[str], operator.add]

    # Counter to prevent the critic from retrying forever
    retries: int    

    # The decision made by the Orchestrator
    next_node: str

    # Tracks which step of the pipeline we're on (deterministic routing)
    current_step: int

