from nbclient import NotebookClient
import nbformat
import base64
import hashlib
import os
import sys
import traceback
import warnings
import logging
from app.agents.state import AgentState
from langchain_core.messages import AIMessage

# --- Suppress all the annoying Jupyter/zmq warnings ---
# 1. Suppress "Proactor event loop does not implement add_reader" RuntimeWarning
if sys.platform == "win32":
    import asyncio
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

# 2. Suppress "[IPKernelApp] WARNING | Kernel is running over TCP without encryption"
logging.getLogger("IPKernelApp").setLevel(logging.ERROR)
logging.getLogger("traitlets").setLevel(logging.ERROR)

# 3. Suppress matplotlib "FigureCanvasAgg is non-interactive" UserWarning
warnings.filterwarnings("ignore", message=".*FigureCanvasAgg.*")
warnings.filterwarnings("ignore", category=RuntimeWarning, message=".*Proactor.*")

def executor_node(state: AgentState):
    """The node grabs the code generated by the previous agent, runs it
    and updates the Langgraph state with the results or errors."""
    #Grab the last message(which is the code from the Analyst/Bisualizer)
    last_message = state["messages"][-1].content
    code_to_run = last_message.replace("Generated Code:\n", "")

    #Run the code
    results = execute_python_code(code_to_run)
    
    #Update the state based on what happened
    # Update the state based on what happened
    if results["error"]:
        return {
            "errors": [results["error"]],
            "messages": [AIMessage(content=f"Execution Error:\n{results['error']}")],
            "retries": state.get("retries", 0) + 1,
            # Preserve any existing chart_paths (unlikely on error)
            "chart_paths": state.get("chart_paths", []),
        }
    else:
        # Merge any existing chart_paths (from visualizer) with new images generated by Plotly fallback (if any)
        existing = state.get("chart_paths", [])
        new_images = results.get("images", [])
        combined = list(set(existing + new_images))
        return {
            "messages": [AIMessage(content=f"Execution Output:\n{results['output']}")],
            "chart_paths": combined,
            "retries": 0,
        }



def execute_python_code(code:str) -> dict:
    """Executes the Python code safely inside an isolated Jupyter Notebook Kernel.
    Returns any printed output, errors, and base64 encoded images."""

    #Create an empty notebook structure
    nb = nbformat.v4.new_notebook()
    #Add a cell with out generated code
    nb.cells.append(nbformat.v4.new_code_cell(code))
    #Initialize a client to run the notebook
    client = NotebookClient(nb, timeout = 60, kernel_name = "python3")
    result = {
        "output": "",
        "error": None,
        "images": [] # We will store the generated charts here
    }
    try:
        # Suppress Jupyter kernel subprocess warnings (IPKernelApp TCP warning)
        # by redirecting stderr at the OS file-descriptor level
        stderr_fd = sys.stderr.fileno()
        saved_stderr = os.dup(stderr_fd)
        devnull = os.open(os.devnull, os.O_WRONLY)
        os.dup2(devnull, stderr_fd)
        
        try:
            #Execute the code
            executed_nb = client.execute()
        finally:
            # Always restore stderr so real errors can still print
            os.dup2(saved_stderr, stderr_fd)
            os.close(devnull)
            os.close(saved_stderr)

        #Parse the outputs from the executed cell
        #Parse the outputs from the executed cell
        for output in executed_nb.cells[0].outputs:
            if output.output_type == "stream":
                result["output"] += output.text
            elif output.output_type == "execute_result" or output.output_type == "display_data":
                if 'text/plain' in output.data:
                    result["output"] += output.data['text/plain'] + "\n"
                
                # If a chart is generated
                if 'image/png' in output.data:
                    os.makedirs("sandbox", exist_ok=True)
                     # Create a filename based on the actual image data!
                 # Identical images will generate the exact same hash and overwrite each other.
                    image_hash = hashlib.md5(output.data['image/png'].encode('utf-8')).hexdigest()[:8]
                    filename = f"sandbox/chart_{image_hash}.png"
                 
                    image_data = base64.b64decode(output.data['image/png'])
                    with open(filename, "wb") as f:
                        f.write(image_data)
                     
                    result["images"].append(filename)
                    
            elif output.output_type == "error":
                result["error"] = "\n".join(output.traceback) 

    except Exception as e:
        result["error"] = traceback.format_exc()
    return result
       